### ISSUE TITLE
getServer() isn't working

### ISSUE THREAD

**Issue by TahaTheHacker** [TahaTheHacker/Anvil#17]
On Timer.php when i use getServer() i get this:
Fatal error: Call to undefined method TahaTheHacker\Anvil\Timer::getServer() in phar://C:/Users/lol/Desktop/lol/lol/lol/plugins/phar_Anvil-master_may4vXZpiVcO1cq.phar/src/TahaTheHacker/Anvil/Timer.php on line 26

**Comment by TahaTheHacker** [comment]
Perfect/.

**Comment by Gamecrafter** [comment]
@TahaTheHacker Learn PHP, along with OOP. If you don't know what they are, use Google.

**Comment by MajikalPayton** [comment]
The onCmd function in class Main is pointless, heads up; I'm going to send a PR without it.
